@host=http://localhost:5030

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNzI1OTA2MC1kMjE2LTQ3OGMtODY5ZS1hNGNhZmE0OGYxNTIiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6ImQ0M2UyNzQwLWYzM2QtNGQyNS1iMTRjLTliN2IyYTY4NDVmZiIsImV4cCI6MTc3MDExNjg0NywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.h0WqfVpoJ15KA0fYIs3D7dIMQSYCWb_o_oAPxRYHxtY
